// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApplication1.Data;

#nullable disable

namespace WebApplication1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("WebApplication1.Models.Gather", b =>
                {
                    b.Property<int>("IdGather")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Idmushroom")
                        .HasColumnType("int");

                    b.Property<int>("idmushroom_picker")
                        .HasColumnType("int");

                    b.HasKey("IdGather");

                    b.HasIndex("Idmushroom");

                    b.HasIndex("idmushroom_picker");

                    b.ToTable("Gathers");
                });

            modelBuilder.Entity("WebApplication1.Models.Mushroom", b =>
                {
                    b.Property<int>("Idmushroom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Class")
                        .HasColumnType("longtext");

                    b.Property<bool?>("Edibility")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("Market_price")
                        .HasColumnType("int");

                    b.Property<string>("Mushroom_birthplace")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<string>("Rarity")
                        .HasColumnType("longtext");

                    b.HasKey("Idmushroom");

                    b.ToTable("Mushrooms");
                });

            modelBuilder.Entity("WebApplication1.Models.Mushroom_picker", b =>
                {
                    b.Property<int>("idmushroom_picker")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("name")
                        .HasColumnType("longtext");

                    b.Property<int>("yearbirth")
                        .HasColumnType("int");

                    b.HasKey("idmushroom_picker");

                    b.ToTable("mushroom_picker");
                });

            modelBuilder.Entity("WebApplication1.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Password")
                        .HasColumnType("longtext");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<string>("Username")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApplication1.Models.Gather", b =>
                {
                    b.HasOne("WebApplication1.Models.Mushroom", "Mushroom")
                        .WithMany()
                        .HasForeignKey("Idmushroom")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApplication1.Models.Mushroom_picker", "Mushroom_Picker")
                        .WithMany()
                        .HasForeignKey("idmushroom_picker")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mushroom");

                    b.Navigation("Mushroom_Picker");
                });
#pragma warning restore 612, 618
        }
    }
}
